name: Daily Update

on:
  schedule:
    - cron: '0 3 * * *'  # 每天北京时间 11:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate HTML
        run: python fetch.py

      - name: Deploy
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add index.html
          git diff --cached --quiet || git commit -m "update $(date +'%Y-%m-%d')"
          git push
